###
POST https://milliways-dev-ed.develop.my.salesforce-sites.com/services/apexrest/healthtracker/ HTTP/1.1
Content-Type: application/json

{
    "environment": "Test",
    "compressedData": "NobwRAJghgLgpmAXGATABhQFgLRoGzYoCsYANGAM4CeFMA9gDYCWAxkmAIwoDMZkTUWo1btuKDnwDucJgHMAFjHZdeAXwC6QA"
}

###
GET https://milliways-dev-ed.develop.my.salesforce-sites.com/services/apexrest/healthtracker/Test HTTP/1.1

###
POST https://milliways-dev-ed.develop.my.salesforce-sites.com/services/apexrest/healthtracker/ HTTP/1.1
Content-Type: application/json

{
    "environment": "Production",
    "compressedData": "H4sIAAAAAAAAA0tJLS4BAAx/f9gEAAAA"
}

###
GET https://milliways-dev-ed.develop.my.salesforce-sites.com/services/apexrest/healthtracker/Production HTTP/1.1



